Makefile
internal/tailscale/client.go
internal/tailscale/client_test.go
tailscale/resource_acl_test.go

Fixes #11
Adds support for both the `Tests` and `TagOwners` fields in ACL configuration. These were previously not included
in the request to the ACL endpoint. Updates the acceptance test to include a full ACL and adds a test to ensure
JSON marshalling of the ACL works as expected.

Add support for TagOwners and Tests in ACL configuration

---

docs/index.md
examples/main.tf
internal/tailscale/client.go
internal/tailscale/client_test.go
tailscale/provider.go
tailscale/provider_test.go
tailscale/resource_acl.go

The Tailscale API's lingo has changed, instead of calling them domains they're now
referred to as tailnets. The provider has been updated so that the work tailnet
is now expected instead.

Change references to "domains" to "tailnets".

---

docs/resources/device_subnet_routes.md
internal/tailscale/client.go
tailscale/provider.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_subnet_routes_test.go

Adds a `device_subnet_routes` resource to the provider, allowing users to specify which
subnet routes are enbaled to be routed by a device.

Add terraform resource for device_subnet_routes

---

tailscale/resource_acl.go
tailscale/resource_dns_nameservers.go
tailscale/resource_dns_preferences.go
tailscale/resource_dns_search_paths.go

Realised each of the schema.Resource types provides a description field, so have copied in text
to match the documentation.

Add descriptions to all current resources

---

docs/data-sources/device.md
docs/resources/device_subnet_routes.md
internal/tailscale/client.go
tailscale/data_source_device.go
tailscale/provider.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_subnet_routes_test.go

In order to use resources like `tailscale_device_subnet_routes`, users will need to be able to provide
a device identifier. This commit adds the ability to obtain a device identifier using a new `tailscale_device`
data source, where a name is provided to obtain the device identifier, which can then be used by other
resources.

Add device data source

---

internal/tailscale/client.go

This commit removes fields that are not directly used by the terraform provider from
the `Device` type.
This change is required to fix #24, as the API returns blank strings for dates, resulting in
errors unmarshalling the JSON response into a `Device` type. Since it's unlikely the provider
will ever need these dates, we can just remove them. The provider also only exposes the id
and name, so everything else can be removed for now too.

Remove unused device fields

---

docs/index.md

This commit fixes #19 by providing additional context on the value of the `tailnet`
field in the provider block.

Describe tailnet format in documentation

---

docs/resources/device_subnet_routes.md

The correct HCL should prefix the data field with `data.`.

Fix incorrect HCL in device subnet routes

---

internal/tailscale/client.go

This commit removes a leading whitespace in the path when attempting to
set device subnet routes via the API. Due to the extra whitespace the
call was actually hitting the UI instead of than API with a POST request,
causing the issue with the invalid CSRF token.
Fixes #29

Remove leading whitespace from path

---

internal/tailscale/client.go

This commit fixes #31 by removing whitespace that was left in front of the
uri path when calling the device subnet route endpoint.

Remove whitespace in device subnet route uri

---

docs/resources/acl.md
examples/main.tf

This commit modifies the example/documentation for ACLs to use the `jsonencode` function
instead of heredocs.
Closes #36

Update ACL examples to use jsonencode

---

docs/data-sources/device.md
docs/data-sources/devices.md
internal/tailscale/client.go
tailscale/data_source_device.go
tailscale/data_source_devices.go

Adds  'addresses' to the `tailscale_device`and `tailscale_devices` resources for IP address lookups.

add 'addresses' field to device and devices resources

---

docs/resources/device_authorization.md
internal/tailscale/client.go
internal/tailscale/client_test.go
tailscale/provider.go
tailscale/resource_device_authorization.go
tailscale/resource_device_authorization_test.go

This commit introduces the `tailscale_device_authorization` resource. This resource allows you to approve devices to join your tailnet via the terraform provider. Device authorization is explained in more detail within [Tailscale's documentation](https://tailscale.com/kb/1099/device-authorization/).
One caveat to this resource is that the Tailscale API [does not support removing authorization](https://github.com/tailscale/tailscale/blob/main/api.md#post-body-1) from a device. So an update from true to false or removal of the resource will not affect the authorized status of the device.
Closes #42

Implement device_authorization resource

---

docs/data-sources/device.md
docs/data-sources/devices.md
internal/tailscale/client.go
tailscale/data_source_device.go
tailscale/data_source_devices.go

Adds a user attribute to the `tailscale_device` and `tailscale_devices` data sources, so we can access the user associated with a device.
**Which issue this PR fixes**: 
Fixes #48 
I haven't run the acceptance tests as I don't have a test tailscale account to test against.

Add 'user' field to device and devices data sources

---

.github/workflows/ci.yml
.github/workflows/release.yml
tailscale/provider.go
tailscale/provider_test.go
tailscale/resource_acl_test.go
tailscale/resource_device_authorization_test.go
tailscale/resource_device_subnet_routes_test.go
tailscale/resource_dns_nameservers_test.go
tailscale/resource_dns_preferences_test.go
tailscale/resource_dns_search_paths_test.go
tailscale/tailscale_test.go

This commit makes some progress on #43, by making the acceptance tests runnable using a mocked
HTTP client. This should at least allow us to catch errors that occur from incorrectly set up
resources/data sources.
It also makes the acceptance tests runnable without requiring a testing environment or the
`TF_ACC` environment variable.
Because these tests currently can take 10s or so to run, I've added caching to the CI.

Make acceptance tests generally runnable

---

tailscale/resource_device_subnet_routes.go

This PR changes DeviceSubnetRoutes to have TypeSet instead of TypeList.
TypeList requires the items to be in a specific order; TypeSet does not. Using TypeList can result in unnecessary change detection if output returned by TS API (which does not appear to return in a fully deterministic or sorted order) is in a different order than input. It also makes diffs more difficult to read if e.g. you add a route mid-list and it detects all routes after that as changed.
In my testing, at least, this change appears to migrate cleanly from the previous version with TypeList.
Fixes #57
**Special notes for your …

switch resource type for DeviceSubnetRoutes.routes to Set

---

docs/resources/tailnet_key.md
internal/tailscale/client.go
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

It lets users preselect ACL tags to use for the machines authenticated by a key.
See https://tailscale.com/kb/1068/acl-tags/#generate-an-auth-key-with-an-acl-tag

Add tags support to auth keys

---

internal/tailscale/client.go
internal/tailscale/client_test.go
tailscale/resource_tailnet_key.go

This commit modifies the `tailnet_key` resource slightly so that one-off keys no longer being present
will not result in errors.
To do this, deletions that result in a 404 error will no longer return an error. Any other errors returned
via the API will still impact it. When reading keys, if a 404 error is returned and the key is not reusable
within the state, it will no longer return an error.
Closes #59

Handle disappearing one-off authentication keys

---

.github/workflows/ci.yml

This commit modifies the CI workflow to only run when pushed to master or on
pull requests. This avoids the CI running twice when a pull request is opened/synced.

Modify GitHub actions workflow to reduce redundant runs

---

docs/data-sources/device.md
docs/data-sources/devices.md
docs/resources/device_tags.md
tailscale/data_source_device.go
tailscale/data_source_devices.go
tailscale/provider.go
tailscale/resource_device_tags.go
tailscale/resource_device_tags_test.go

This commit introduces the `tailscale_device_tags` resource which allows the user to apply ACL tags
to individual devices. The `tailscale-client-go` package has been updated to 1.1.0 which includes
methods for modifying device tags.
Closes #67

Implement device_tags resource

---

docs/data-sources/device.md
tailscale/data_source_device.go
tailscale/provider.go
tailscale/resource_device_tags_test.go

This commit adds a new argument to the `tailscale_device` data source that allows for the configuration
of a retry mechanism. If this argument is provided, the provider will retry obtaining device data every
second up until the maximum duration specified in the `wait_for` argument.
This argument is optional, if it is not specified then the first error will fail the read. The field
is expected to use the string representation of go's `time.Duration` type.
Closes #69 (nice)

Add wait_for argument to tailscale_device data source

---

go.mod
go.sum
tailscale/provider.go
vendor/github.com/davidsbond/tailscale-client-go/tailscale/client.go
vendor/modules.txt

Closes #73
This commit adds additional error details when an error response from the API contains entries in its `Data` field. These
errors are typically returned from failing ACL tests. Each error is given its own diagnostic describing the user and the
error.

Add additional errors to diagnostics

---

docs/resources/device_key.md
go.mod
go.sum
tailscale/provider.go
tailscale/resource_device_key.go
tailscale/resource_device_key_test.go
vendor/github.com/davidsbond/tailscale-client-go/tailscale/client.go
vendor/modules.txt

Closes #78
This commit introduces the `tailscale_device_key` resource which is used to modify the properties of the device's key.
Currently, this resource can disable device key expiry and pre-authorize a device for the tailnet. The read operation
checks the value of the device's `authorized` and `keyExpiryDisabled` fields, as there's no way to read the key properties
directly.

Add tailscale_device_key resource

---

tailscale/provider.go

Closes #91
Terraform will crash when adding errors that do not include the summary field. This
commit adds extra error data to the summary field instead of the detail field.

Add error data to summary field instead of detail field

---

README.md
docs/index.md
tailscale/provider.go

Allow users to declare the baseurl in the provider block. Add a new baseurl variable.
fixes https://github.com/davidsbond/terraform-provider-tailscale/issues/97

Allow declaration of tailscale api endpoint

---

.github/workflows/ci.yml
.goreleaser.yml
Makefile
go.mod
go.sum
tailscale/data_source_device.go
tailscale/data_source_devices.go
tailscale/provider.go
tailscale/provider_test.go
tailscale/resource_acl.go
tailscale/resource_device_authorization.go
tailscale/resource_device_authorization_test.go
tailscale/resource_device_key.go
tailscale/resource_device_key_test.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_subnet_routes_test.go
tailscale/resource_device_tags_test.go
tailscale/resource_dns_nameservers.go
tailscale/resource_dns_preferences.go
tailscale/resource_dns_search_paths.go
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go
tailscale/tailscale_test.go
tools.go

This commit runs goimports across all source files to move local
imports to a separate block. It also removes old comments from the
goreleaser configuration & adds a new GitHub actions job that will
check the formatting and error if go fmt and goimports change
the committed code.

Format all files, add formatting CI step

---

.github/workflows/ci.yml

**What this PR does / why we need it**: Updates CI triggers
- Run on main instead of master. Updates https://github.com/tailscale/terraform-provider-tailscale/issues/140
- Run on (and so not block) markdown changes, like https://github.com/tailscale/terraform-provider-tailscale/pull/138 and https://github.com/tailscale/terraform-provider-tailscale/pull/139

Update ci triggers

---

.github/workflows/ci.yml
CONTRIBUTING.md
Makefile
README.md
docs/index.md
examples/provider/provider.tf
go.mod
go.sum
main.go
tailscale/data_source_device.go
tailscale/data_source_devices.go
tailscale/provider.go
tailscale/provider_test.go
tailscale/resource_acl.go
tailscale/resource_device_authorization.go
tailscale/resource_device_authorization_test.go
tailscale/resource_device_key.go
tailscale/resource_device_key_test.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_subnet_routes_test.go
tailscale/resource_device_tags.go
tailscale/resource_device_tags_test.go
tailscale/resource_dns_nameservers.go
tailscale/resource_dns_preferences.go
tailscale/resource_dns_search_paths.go
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go
tailscale/tailscale_test.go

Also:
- switch to go 1.19
- go mod tidy
renames module from davidsbond namespace to tailscale (thank you, David!)
Fixes #141

update module name

---

.github/CODE_OF_CONDUCT.md

**What this PR does / why we need it**: Changes code of conduct from Terraform provider default (HashiCorp coc) to Contributor Covenant (Tailscale default).
**Which issue this PR fixes** *(use `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:  n/a
Fixes #

CODE_OF_CONDUCT: update to contributor covenant

---

README.md

**What this PR does / why we need it**: Updates repo description to clarify it is maintained by Tailscale
Did not update references to Terraform provider in new namespace, which is not published yet.
**Which issue this PR fixes** *(use `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: n/a
Fixes #

README: update description to maintained by Tailscale

---

docs/resources/tailnet_key.md
examples/resources/tailscale_tailnet_key/resource.tf
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

Adds key expiration option to the `tailscale_tailnet_key` resource
**Which issue this PR fixes** 
N/A
See https://github.com/tailscale/tailscale-client-go/pull/34 for associated client change

Add key expiration to tailscale_tailnet_key

---

go.mod
go.sum
tailscale/resource_tailnet_key.go

This updates the client library to pick up tailscale/tailscale-client-go#37 and correctly passed key expiration time.
Closes #184.

tailscale_tailnet_key: correctly set key expiration

---

go.sum
tailscale/resource_acl.go

Overwriting non-default ACL contents is confusing, so now users will be prompted to explicitly import their existing ACL into Terraform if they want to manage it there. This will make overwriting existing contents harder, since after importing Terraform will show a sensible diff in `terraform apply`.
Fixes #182.

Do not overwrite ACL file that has been changed manually

---

README.md

Bump provider version in README to [latest available (v0.13.6)](https://github.com/tailscale/terraform-provider-tailscale/releases/tag/v0.13.6) as of December 1 2022.

Docs: Bump provider version in README to latest

---

tailscale/resource_device_subnet_routes.go

The error message on `read` operations of `tailscale_device_subnet_routes` referred to name servers instead of device routes. This fixes the error message to refer to the correct resource type.

tailscale_device_subnet_routes: Fix confusing error message

---

docs/resources/tailnet_key.md
tailscale/resource_tailnet_key.go

Expose two new fields on `tailscale_tailnet_key`, "expires_at" and "created_at", which are just lifted from the Tailscale API response.
**Which issue this PR fixes** 
Fixes #194
Opted to go with "expires_at/created_at" instead of "expires/created", but can switch if that's preferred.

Expose "created_at" and "expired_at" timestamps for Tailnet Keys.

---

README.md
docs/index.md
tailscale/provider.go

- Use a default version for the `tailnet` configuration parameter and remove it from the example;
- Suggest a weaker version constraint that uses the latest patch release;
- Document using OAuth client credentials rather than personal API keys;
- Make it more clear that setting `base_url` is only necessary if you are using a non-default coordination server.
Fixes #207
Fixes #243

README.md: update defaults and examples

---

docs/resources/tailnet_key.md
examples/resources/tailscale_tailnet_key/resource.tf
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

Adding the ability to define a description when creating a key. I've included an example, updated the docs with tfplugindocs, and added `description` to test.
Fixes #
Following on from addition in [the API](https://github.com/tailscale/tailscale-client-go/pull/53).

Add tailscale tailnet key Description and update docs

---

docs/resources/device_key.md
docs/resources/tailnet_key.md
tailscale/resource_device_key.go
tailscale/resource_tailnet_key.go

Documents the optional resource properties for `device_key` and `tailnet_key` resources.
Fixes #291 

Document defaults for `device_key` and `tailnet_key`

---

docs/resources/acl.md
docs/resources/dns_preferences.md
examples/resources/tailscale_acl/import.sh
examples/resources/tailscale_dns_preferences/import.sh
tailscale/resource_dns_preferences.go

Also document importing tailscale_acl resources, which was supported from #186.
Partially takes over #125, but only for a resource I'm actively testing. Others can follow in a future PR.
@clstokes @davidsbond

Support importing tailscale_dns_preferences resources.

---

docs/resources/tailnet_key.md
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

This change partially reverts the behaviour introduced in #287 that currently results in single-use keys being recreated, triggering unnecessary updates to downstream Terraform resources.
By default, the provider will now only recreate reusable keys, ignoring invalid single-use keys. This can also be changed now using a new `recreate_if_invalid` attribute.
Fixes #306

tailscale_tailnet_key: only recreate reusable keys by default

---

docs/resources/acl.md
tailscale/resource_acl.go

Document that ACL tests are run when creating and updating tailscale_acl resources.

---

tailscale/resource_tailnet_key.go

This adds validation logic to the tailnet key resource to ensure the description doesn't exceed 50 characters
Fixes #320

validate the description length for tailnet keys

---

docs/data-sources/4via6.md
tailscale/data_source_4via6.go
tailscale/data_source_4via6_test.go

**What this PR does / why we need it**: Fixes a bug in the site id limits
**Which issue this PR fixes** *(use `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:  fixes #346

Increase allowed 4via6 site ids

---

.goreleaser.yml
main.go
tailscale/provider.go

The `schema.Provider.UserAgent` helper function was previously being called at a point in the plugin lifecycle before the `TerraformVersion` for the provider was set by Terraform Core. This was resulting in the Terraform version information being missing from the User-Agent header. The call to `schema.Provider.UserAgent` has now been moved into the `providerConfigure` func as this is called later in the configure lifecycle where the Terraform version is properly set.
`Terraform/ (+https://www.terraform.io) Terraform-Plugin-SDK/2.33.0 terraform-provider-tailscale/dev`
`Terraform/1.8.2 (+https://www.terraform.io) Terraform-Plugin-SDK/2.33.0 terraform-provider-tailscale/dev`
Fixes https://github.com/tailscale/corp/issues/19630

tailscale: fix default User-Agent header to include terraform version

---

tailscale/resource_device_authorization.go
tailscale/resource_device_key.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_tags.go
tailscale/resource_dns_nameservers.go
tailscale/resource_dns_preferences.go
tailscale/resource_dns_search_paths.go
tailscale/resource_dns_split_nameservers.go
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

Add calls to appropriate `Read` functions at the end of `Create` and `Update` functions to follow recommended best practices from HashiCorp. This is done to prevent scenarios where Terraform could otherwise have stale state after resource creation or update (from default or computed values being populated server side on the object as an example) which can result in unexpected drift in subsequent plan / apply operations.
Fixes https://github.com/tailscale/corp/issues/19698

tailscale: update state after modification functions for resources

---

tailscale/resource_dns_split_nameservers.go

Currently if you use import on `tailscale_dns_split_nameservers`, the `domain` attribute will get set to `null` in the terraform state, and thus will result in 
Since the resource ID and domain are the same, set domain to the resource ID.
sample code:
```
import {
to = tailscale_dns_split_nameservers.example-com
id = "example.com"
}
resource "tailscale_dns_split_nameservers" "example-com" {
domain      = "example.com"
nameservers = [
"1.2.3.4",
"5.6.7.8"
]
}
```
Before:
```
~ resource "tailscale_dns_split_nameservers" "example-com" {
+ domain      = "example.com"
id          = "example.com"
nameservers = [
"1.2.3.4",
"5.6.7.8"
]
}
```
after:
```
resource "tailscale_dns_split_nameservers" "example-com" {
domain      = "example.com"
id          = …
```

fix imports for splitdns

---

tailscale/resource_acl.go

Adds calls to `Read` after doing `Create` or `Update` operations for the ACL resource. This resource was missed in #362 where it was added for other existing resources.
Fixes https://github.com/tailscale/corp/issues/19698

tailscale: update state after modification for ACL resource

---

.github/workflows/release.yml

As per https://goreleaser.com/deprecations/#__tabbed_17_1 `--rm-dist` has been deprecated in favour of `--clean`.

.github/workflows: use --clean instead of deprecated --rm-dist

---

README.md

Add a new `Local Provider Development` section to the README which links to the HashiCorp provider plugin debugging guide and provides an example of using the `dev_overrides` block in `terraformrc` to help those newer to terraform get their local environment setup for development.
Fixes https://github.com/tailscale/corp/issues/20371

README.md: explain dev_overrides for local provider development

---

README.md
tailscale/provider_test.go
tailscale/resource_webhook_test.go

Add initial acceptance testing setup logic and a basic acceptance test for the new webhook resource.
Updates https://github.com/tailscale/corp/issues/21842

tailscale: add initial acceptance testing logic

---

README.md
docs/resources/device_authorization.md
examples/resources/tailscale_device_authorization/import.sh
tailscale/provider_test.go
tailscale/resource_device_authorization.go
tailscale/resource_device_authorization_test.go

Add basic acceptance test for device_authorization. Also add logic to allow for importing `device_authorization` while I was here.
Updates https://github.com/tailscale/corp/issues/21842

tailscale: add acceptance test for device_authorization

---

go.mod
go.sum
tailscale/data_source_acl.go
tailscale/data_source_device.go
tailscale/data_source_devices.go
tailscale/provider.go
tailscale/provider_test.go
tailscale/resource_acl.go
tailscale/resource_contacts.go
tailscale/resource_contacts_test.go
tailscale/resource_device_authorization.go
tailscale/resource_device_key.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_tags.go
tailscale/resource_dns_nameservers.go
tailscale/resource_dns_preferences.go
tailscale/resource_dns_search_paths.go
tailscale/resource_dns_split_nameservers.go
tailscale/resource_tailnet_key.go
tailscale/resource_webhook.go
tailscale/resource_webhook_test.go
tailscale/tailscale_test.go

We want to switch to using the new v2 of the tailscale-go-client. This initializes the appropriate clients so that we can start using them.

tailscale: add support for using v2 tailscale-client

---

go.mod
go.sum
tailscale/resource_device_authorization.go
tailscale/resource_device_authorization_test.go

Depends on:
- https://github.com/tailscale/terraform-provider-tailscale/pull/388
- https://github.com/tailscale/tailscale-client-go/pull/90

tailscale: use V2 client for Devices

---

go.mod
go.sum
tailscale/resource_webhook.go
tailscale/resource_webhook_test.go

Depends on https://github.com/tailscale/tailscale-client-go/pull/91

tailscale: use V2 client for Webhooks

---

README.md

Add small blurb to README.md explaining release process.

README.md: add blurb about release process

---

tailscale/resource_device_key.go
tailscale/resource_device_key_test.go

tailscale: use v2 client for device keys

---

tailscale/resource_device_authorization_test.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_subnet_routes_test.go

Acceptance test [passed](https://github.com/tailscale/corp/actions/runs/10308138358).

tailscale: use v2 client for device subnet routes

---

.gitignore

Add `terraform-provider-tailscale` to .gitignore.

.gitignore: ignore provider binary

---

tailscale/resource_dns_nameservers.go
tailscale/resource_dns_nameservers_test.go

tailscale: use v2 client for dns nameservers

---

tailscale/resource_acl_test.go
tailscale/resource_dns_preferences_test.go
tailscale/resource_tailnet_settings_test.go

Instead, return errors to allow acceptance test scaffolding to report failures as conventional.

tailscale: don't use t.Fatal in acceptance tests

---

tailscale/data_source_acl.go
tailscale/data_source_acl_test.go
tailscale/provider_test.go
tailscale/resource_acl_test.go
tailscale/resource_dns_nameservers_test.go
tailscale/resource_dns_preferences_test.go
tailscale/resource_dns_search_paths_test.go
tailscale/resource_tailnet_key_test.go
tailscale/resource_tailnet_settings_test.go

tailscale: use V2 client for acl data source

---

docs/resources/dns_split_nameservers.md
go.mod
go.sum
tailscale/resource_dns_split_nameservers.go
tailscale/resource_dns_split_nameservers_test.go

Depends on https://github.com/tailscale/tailscale-client-go/pull/104

tailscale: use V2 client for dns split nameservers resource

---

tailscale/data_source_4via6_test.go
tailscale/data_source_acl_test.go
tailscale/data_source_device.go
tailscale/data_source_devices.go
tailscale/data_source_user.go
tailscale/data_source_users.go
tailscale/data_source_users_test.go
tailscale/datasource_devices_test.go
tailscale/provider_test.go
tailscale/resource_acl_test.go
tailscale/resource_contacts_test.go
tailscale/resource_device_authorization_test.go
tailscale/resource_device_key_test.go
tailscale/resource_device_subnet_routes_test.go
tailscale/resource_device_tags_test.go
tailscale/resource_dns_nameservers_test.go
tailscale/resource_dns_preferences_test.go
tailscale/resource_dns_search_paths_test.go
tailscale/resource_dns_split_nameservers_test.go
tailscale/resource_logstream_configuration_test.go
tailscale/resource_posture_integration_test.go
tailscale/resource_tailnet_key_test.go
tailscale/resource_tailnet_settings_test.go
tailscale/resource_webhook_test.go
tailscale/tailscale_test.go

This allows the reuse of private functions like deviceToMap between the core package and the tests.

tailscale: rename tailscale_test package to tailscale

---

docs/resources/device_subnet_routes.md
tailscale/resource_device_subnet_routes.go

Add better documentation to the device_subnet_routes resource to clarify that routes need to be advertised on the device itself, and that all routes (including those enabled via the admin console / autoApprovers in the ACL) must be added to the `routes` param when using this resource to avoid configuration drift.
Updates https://github.com/tailscale/corp/issues/22115

{docs,tailscale}: better document device_subnet_routes

---

go.mod
go.sum
tailscale/provider.go

Update tailscale-client-go dependency and modify OAuth usage to work with the breaking change in OAuth API that was introduced.
Updates https://github.com/tailscale/corp/issues/21867

tailscale: update to new tailscale client OAuth config pattern

---

tailscale/resource_webhook.go

Add missing `categoryDeviceMisconfigurations` and
`categoryTailnetManagement` event subscriptions to the validation logic for the `subscriptions` property for the webhook resource.
Updates https://github.com/tailscale/terraform-provider-tailscale/issues/433

tailscale: add missing webhook event categories

---

tailscale/provider.go

Pass the `parsedBaseURL` to `tsclient.OAuthConfig`. The base URL the OAuth client used for attempting to generate tokens was always the default URL previously which causes issues if the base URL for the provider and the rest of the tailscale client is set to something else.
Fixes https://github.com/tailscale/terraform-provider-tailscale/issues/438

tailscale: pass base URL to OAuthConfig

---

docs/resources/device_key.md
docs/resources/device_subnet_routes.md
docs/resources/device_tags.md
docs/resources/dns_nameservers.md
docs/resources/dns_search_paths.md
examples/resources/tailscale_device_key/import.sh
examples/resources/tailscale_device_subnet_routes/import.sh
examples/resources/tailscale_device_tags/import.sh
examples/resources/tailscale_dns_nameservers/import.sh
examples/resources/tailscale_dns_search_paths/import.sh
tailscale/resource_device_key.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_tags.go
tailscale/resource_dns_nameservers.go
tailscale/resource_dns_search_paths.go

Some tailscale terraform resources were missing import capabilities.
**Which issue this PR fixes** _(use `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)_:
Fixes #441

Add missing importer logic

---

docs/resources/logstream_configuration.md
docs/resources/posture_integration.md
examples/resources/tailscale_logstream_configuration/import.sh
examples/resources/tailscale_posture_integration/import.sh
tailscale/resource_device_key_test.go
tailscale/resource_device_subnet_routes.go
tailscale/resource_device_subnet_routes_test.go
tailscale/resource_device_tags_test.go
tailscale/resource_dns_nameservers_test.go
tailscale/resource_dns_search_paths_test.go
tailscale/resource_logstream_configuration.go
tailscale/resource_logstream_configuration_test.go
tailscale/resource_posture_integration.go
tailscale/resource_posture_integration_test.go

Add import logic for `posture_integration` and `logstream_configuration` and corresponding acceptance tests.
Add acceptance tests to exercise import logic that was recently added for `device_key`, `device_subnet_routes`, `dns_nameservers`, and `dns_search_paths`.
Updates https://github.com/tailscale/terraform-provider-tailscale/issues/441

tailscale: add import logic for remaining resources

---

docs/resources/tailnet_key.md
go.mod
go.sum
tailscale/data_source_acl.go
tailscale/data_source_acl_test.go
tailscale/resource_acl.go
tailscale/resource_acl_test.go
tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

Update acl datasource and resource to use new  type.
Updates tailscale/tailscale-client-go#119

go.mod, tailscale: update to latest tailscale-client-go

---

docs/resources/acl.md
tailscale/resource_acl.go
tailscale/resource_acl_test.go

Add an optional `reset_acl_on_destroy` attribute to the `tailscale_acl` resource which causes the ACL on the Taislcale control plane to be reset to the default ACL when the resource is destroyed.
Updates https://github.com/tailscale/terraform-provider-tailscale/issues/426

tailscale: add `reset_acl_on_destroy` attribute to `tailscale_acl`

---

tailscale/resource_tailnet_key.go
tailscale/resource_tailnet_key_test.go

Oversight when we added expiry on the read operation to support imports. We need to mark it as computed so the BE-generated value is used if it's not specified in the schema.
Fixes #520
Demo:
https://github.com/user-attachments/assets/9743b135-af98-4cf6-9aac-706542d5ce3c

resource_tailscale_tailnet_key: prevent recreate when expiry is undefined

---

tailscale/resource_device_subnet_routes.go

This PR improves the resource `tailscale_device_subnet_routes` behavior in two key ways:
1. **Force Resource Recreation on device_id Change**
Added `ForceNew: true` to the `device_id` schema field to ensure the resource is recreated when the device ID changes.
2. **Graceful Handling of Missing Devices**
Updated `resourceDeviceSubnetRoutesRead` to check for a 404 response from the API. If the device no longer exists, the resource ID is cleared to allow Terraform to recreate it instead of failing the plan.
Fixes #526 
**Special notes for your reviewer**: N/A

Handle Missing Devices and Enforce Recreation on device_id Change for tailscale_device_subnet_routes
