- docs/index.md
Simply add a couple of existing env variables to configure the provider in the documentation.
> docs: added the provider configuration env variables

- tailscale/data_source_device.go
- tailscale/data_source_devices.go
Fixes bug introduced in https://github.com/davidsbond/terraform-provider-tailscale/pull/49
Fixes #50
> Set user as a computed attribute, not a required attribute

- tailscale/resource_acl.go
Closes #122
Related to #121
This commit modifies the ACL decoding function to use `json.Decoder` and enables
the `DisallowUnknownFields` flag. This means that when someone using this provider
is trying to use an ACL feature that is not yet supported by the provider, they
will get an error prompting them to raise an issue on GitHub.
Initially, these errors would fail silently and users would be surprised to find
whatever unsupported field they used did not make its way to the Talscale API.
> Error when using an unsupported ACL field

- .github/workflows/release.yml
**What this PR does / why we need it**: Last commit fixed a thing and broke a thing.
Fixes #
> release.yml: checkout before referencing go.mod

- .github/workflows/release.yml
**What this PR does / why we need it**: Unbreak the thing I broke earlier.
Fixes #
> Add PASSPHRASE back to release.yml

- .github/workflows/release.yml
To be able to upload artifacts.
**What this PR does / why we need it**: To be able to upload artifacts.
Fixes #
> Add contents:write permission to releaser.

- go.mod
- go.sum
- tailscale/data_source_4via6.go
- tailscale/data_source_4via6_test.go
> go.mod: update to 1.30.1

- README.md
Need to `terraform state replace-provider`
Explain how to update an existing installation.
> readme: add instructions to update

- .github/workflows/ci.yml
- .github/workflows/release.yml
> .github: use new GITHUB_OUTPUT env var

- docs/resources/acl.md
- tailscale/resource_acl.go
Updates #182.
Signed-off-by: Anton Tolchanov <anton@tailscale.com>
> Document that tailscale_acl overrides the whole ACL file

- tailscale/resource_acl.go
> tailscale_acl skip acl validate & format if it's value is not known yet

- README.md
Bump version of provider in README to 0.16.
> readme: bump version of provider in README

- tailscale/resource_contacts.go
- tailscale/resource_contacts_test.go
> tailscale: use V2 client for Contacts

- go.mod
- go.sum
- tailscale/provider.go
- tailscale/resource_contacts.go
- tailscale/resource_webhook.go
- tailscale/tailscale_test.go
> tailscale: use consistent naming for v2 tailscale client

- tailscale/resource_dns_search_paths.go
- tailscale/resource_dns_search_paths_test.go
> tailscale: use v2 client for dns search paths

- tailscale/resource_dns_preferences.go
- tailscale/resource_dns_preferences_test.go
> tailscale: use v2 client for dns preferences

- tailscale/resource_acl.go
- tailscale/resource_acl_test.go
> tailscale: use v2 client for ACL

- tailscale/resource_tailnet_key.go
- tailscale/resource_tailnet_key_test.go
> tailscale: use v2 client for keys

- tailscale/provider.go
- tailscale/resource_device_tags.go
- tailscale/resource_device_tags_test.go
> tailscale: use v2 client for device tags

- tailscale/data_source_device.go
- tailscale/data_source_devices.go
- tailscale/datasource_devices_test.go
> tailscale: use V2 client for device and devices data sources

- go.mod
- go.sum
- tailscale/data_source_acl.go
- tailscale/data_source_acl_test.go
- tailscale/data_source_device.go
- tailscale/data_source_devices.go
- tailscale/data_source_user.go
- tailscale/data_source_users.go
- tailscale/data_source_users_test.go
- tailscale/datasource_devices_test.go
- tailscale/provider.go
- tailscale/provider_test.go
- tailscale/resource_acl.go
- tailscale/resource_contacts.go
- tailscale/resource_device_authorization.go
- tailscale/resource_device_key.go
- tailscale/resource_device_subnet_routes.go
- tailscale/resource_device_tags.go
- tailscale/resource_device_tags_test.go
- tailscale/resource_dns_nameservers.go
- tailscale/resource_dns_preferences.go
- tailscale/resource_dns_search_paths.go
- tailscale/resource_dns_split_nameservers.go
- tailscale/resource_logstream_configuration.go
- tailscale/resource_posture_integration.go
- tailscale/resource_tailnet_key.go
- tailscale/resource_tailnet_key_test.go
- tailscale/resource_tailnet_settings.go
- tailscale/resource_webhook.go
- tailscale/tailscale_test.go
> tailscale: remove use of client V1

- go.mod
- go.sum
> go.mod: bump tailscale.com to 1.76.3

- .github/workflows/ci.yml
- .github/workflows/release.yml
Pin versions of GitHub actions that are used in our workflows.
> .github/workflows: pin GitHub action versions
